### ISSUE TITLE
Implementation of Gyroscope

### ISSUE THREAD

**Issue by gusmalikah** [DIT112-V21/group-15#18]
We will implement the gyroscope in sprint 2 which will help the emulator to rotate in whatsoever direction at its spot without changing its position. Implementation of a Gyroscope will enhance the ability of the car and also it will improve the object avoidance done by the car in a new way. If we then have obstacles on any 3 sides still we can move the car by just rotating with the help of a gyroscope and then we can move the car to its new path.

**Comment by sam-hashimi** [comment]
We did not go with this idea!
